import { Garment } from '../app/common/services/garment.service';

export const mockGarments: Garment[] = [
    {
        id: '1',
        type: 'Jacket',
        brand: { id: 1, name: 'Ward' },
        color: 'Black',
        name: 'Premium Leather Jacket',
        description: 'High-quality black leather jacket',
        image_url: '/assets/Jacket.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        type: 'Shirt',
        brand: { id: 2, name: 'Stella' },
        color: 'White',
        name: 'Casual Cotton Shirt',
        description: 'Comfortable white cotton shirt',
        image_url: '/assets/Shirt.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        type: 'Pants',
        brand: { id: 3, name: 'Norde' },
        color: 'Blue',
        name: 'Slim Fit Jeans',
        description: 'Modern slim fit jeans in dark blue',
        image_url: '/assets/pants.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        type: 'T-Shirt',
        brand: { id: 4, name: 'Another' },
        color: 'Cream',
        name: 'Graphic Tee',
        description: 'Comfortable graphic printed t-shirt',
        image_url: '/assets/Tshirt.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        type: 'Sweater',
        brand: { id: 5, name: 'Nordic' },
        color: 'Brown',
        name: 'Wool Sweater',
        description: 'Warm wool sweater in gray',
        image_url: '/assets/Sweater.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '6',
        type: 'Jacket',
        brand: { id: 6, name: 'Urban' },
        color: 'Blue',
        name: 'Denim Jacket',
        description: 'Classic denim jacket',
        image_url: '/assets/Jacket.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '7',
        type: 'Accessories',
        brand: { id: 7, name: 'Vintage' },
        color: 'Brown',
        name: 'Corduroy Cap',
        description: 'Warm corduroy cap with patch',
        image_url: '/assets/Accessorie.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const garmentTypes = [
    'T-Shirt',
    'Shirt',
    'Pants',
    'Jacket',
    'Sweater',
    'Dress',
    'Skirt',
    'Shoes',
    'Accessories',
];

export const getMockGarments = (): Garment[] => mockGarments;
