import { Garment } from '../app/common/services/garment.service';

export const mockGarments: Garment[] = [
    {
        id: '1',
        type: 'Jacket',
        brand: 'Ward',
        color: 'Black',
        name: 'Premium Leather Jacket',
        description: 'High-quality black leather jacket',
        image: '/assets/Jacket.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        type: 'Shirt',
        brand: 'Stella',
        color: 'White',
        name: 'Casual Cotton Shirt',
        description: 'Comfortable white cotton shirt',
        image: '/assets/Shirt.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        type: 'Pants',
        brand: 'Norde',
        color: 'Blue',
        name: 'Slim Fit Jeans',
        description: 'Modern slim fit jeans in dark blue',
        image: '/assets/pants.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        type: 'T-Shirt',
        brand: 'Another',
        color: 'Cream',
        name: 'Graphic Tee',
        description: 'Comfortable graphic printed t-shirt',
        image: '/assets/Tshirt.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        type: 'Sweater',
        brand: 'Nordic',
        color: 'Brown',
        name: 'Wool Sweater',
        description: 'Warm wool sweater in gray',
        image: '/assets/Sweater.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '6',
        type: 'Jacket',
        brand: 'Urban',
        color: 'Blue',
        name: 'Denim Jacket',
        description: 'Classic denim jacket',
        image: '/assets/Jacket.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '7',
        type: 'Accessories',
        brand: 'Vintage',
        color: 'Brown',
        name: 'Corduroy Cap',
        description: 'Warm corduroy cap with patch',
        image: '/assets/Accessorie.svg',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const getMockGarments = (): Garment[] => mockGarments;
